# Generated by Django 5.0.3 on 2024-03-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.URLField(null=True)),
                ('download_url', models.URLField(null=True)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
