# Generated by Django 5.0.3 on 2024-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artist_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.URLField(null=True)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('is_explict', models.BooleanField(default=False)),
            ],
        ),
    ]
