# Generated by Django 5.0.3 on 2024-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_remove_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(default='pop', max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='language',
            field=models.CharField(default='ru', max_length=100),
        ),
    ]
