# Generated by Django 5.0.3 on 2024-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_track_genre_track_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
