# Generated by Django 5.0.3 on 2024-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='download_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
