# Generated by Django 5.0.3 on 2024-03-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_track_download_url_alter_track_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
